# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b08ddcf4dec1cd8a14d1d753fcfec89ba631a0483212f2503d51cab09f55559fc51d3ae16b11a552b86d5db2997b71cdbd27c716bdc74af0ade22363fd2570e

test:
  secret_key_base: e1262ee4c408091ecf3bf2f5ebba1315ba294e31d6967925d47a768e728d8be90ebb2c049424e3a9e8b56ce61349839429e569e760adc87ad4ff38b9cae35235

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
